### ISSUE TITLE
Release 0.5.1

### ISSUE THREAD

**Issue by tmcw** [fraserxu/react-chartist#13]
Right now the 0.5.0 release is broken because of https://github.com/fraserxu/react-chartist/commit/828360d602a2d98380515bd73598b4c1bc011292 and 0.5.1 hasn't been pushed to npm.

**Comment by fraserxu** [comment]
Ah sorry @tmcw I forgot to publish the new release after pushing to Github.

**Comment by fraserxu** [comment]
Just pushed and tested. Thanks for letting me know!
