### ISSUE TITLE
Configure Chartist as a peer dependency to prevent duplicate imports

### ISSUE THREAD

**Issue by larrybotha** [fraserxu/react-chartist#41]
When using easing functions all available on the Chartist library itself, Chartist needs to be imported into whichever module the ChartistGraph component is being used, too.

Looking at the compiled js, this results in a duplicate Chartist import.

Moving Chartist from `dependencies` to `peerDependencies` should fix this.

As a workaround in the meantime, Chartist can be aliased in the Webpack config:

``` javascript
// webpack.config.js
...
  resolve: {
    alias: {
      ...
      chartist: path.resolve(__dirname, 'node_modules/chartist'),
      ...
    },
  },
...
```

@fraserxu would you like me to submit a quick PR for this?

**Comment by fraserxu** [comment]
Would appreciate for it!

**Comment by davidthornton** [comment]
Would using es6 and yarn (and having react-chartist configured as a proper dependency) solve this issue?

If so, I recommend the future-proof solution would be to depend on chartist and use es6 and yarn to import the underlying chartist symbols?
