### ISSUE TITLE
@types/chartist need to be runtime dependency

### ISSUE THREAD

**Issue by rosskevin** [fraserxu/react-chartist#76]
https://github.com/fraserxu/react-chartist/commit/009cdb7a85c29917395382a56e8e281113e39a30

If you are going to export types as part of the repo, you need to cause package consumers to import transitive dependencies.  In this case, you need to cause ts users to import `@types/chartist` by moving it to `dependencies` in the package.json.

This has a zero impact on bundle size.

**Comment by fraserxu** [comment]
A consume should be able to `npm i @types/chartist --save-dev` as a `devDependencies` and just works if I'm not missing any thing.

**Comment by rosskevin** [comment]
A consumer can do that, but that's not what you would tell consumers of the library to do with all your dependencies, so it shouldn't be done with types either.

As I mentioned, it has a zero impact on bundle size.

**Comment by rosskevin** [comment]
The download size is almost nothing. React is not a good example. Most other libraries will provide transitive dependencies needed, not provide additional instructions for all types needed to be downloaded. Feel free to provide more instructions but that makes little sense because the dependencies mechanism is built-in. 

If you don't want to support types in a first class way, no problem, just don't include them in the repo.

**Comment by fraserxu** [comment]
> If you don't want to support types in a first class way, no problem, just don't include them in the repo.

Thanks @rosskevin I have been using TS for a while now and I'm a big fan. But I don't think not including it means we are not supporting it in a first class way. Provide more instructions sound like the best approach for me.

The added download size is not my concern here, but more of what is the best practises for handling a dependencies like this. For me personally, I still feel what's in `dependencies` should be strictly limited to production bundle code only. And type definition is definitely not part of it.

**Comment by rosskevin** [comment]
Your feeling has no practical basis, no pro, just con. It negatively impact ts users and has ~zero impact on non-ts users. 

It is no doubt your choice, just not one that is a benefit to any user.

**Comment by fraserxu** [comment]
Sorry I don't like the way you talk.
