### ISSUE TITLE
Convert to es5

### ISSUE THREAD

**Issue by slonoed** [fraserxu/react-chartist#9]
I also love new cool es6 syntax. But in my apps i really need to exclude node_modules from babel parse. Parse node_modules decrease speed of build.
Can you convert this to es5? Or if I do, will you merge PR?

**Comment by danielberndt** [comment]
One option would be to keep the sources in es6 but add a [`prepublish`](https://docs.npmjs.com/misc/scripts) script which automatically converts the code to es5. 

@slonoed In the meantime you could define your babel step like this to prevent loading _all_ of node_modules (assuming you're using webpack, but I guess other tools support similar patterns):
```
{test: /\.jsx?$/, loader: "babel?experimental", include: [path.resolve(__dirname, "src"), path.resolve(__dirname, "node_modules/react-chartist")]},
```

**Comment by fraserxu** [comment]
Sorry for the inconvenient, I'll compile it to es5 and publish it again.

**Comment by fraserxu** [comment]
Hi @slonoed I included the es5 code inside the `dist/index.js`, and set it as the main entry file, you can just require it in your code now.

By the way the version is `0.5.0`. Let me know if it works for you, thanks.

**Comment by razagill** [comment]
Great, works for me.

**Comment by fraserxu** [comment]
@razagill Thanks for the feedback. I'll close this issue then.
